name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Multi-line command
          run: |
            echo "This is my first action"
            ls -ltra
            more README.md

        - name: Generate ASCII Art
          run: coasay -f dragon "BRRRRR" >> dragon.txt