name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "This is my first GitHub action job what happening"

        - name: List Files
          run: ls

        - name: Read the files
          run: cat README.md
