name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: check out Repo
          uses: actions/checkout@v4

        - name: Install cowsay program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay command
          run: cowsay -f dragon "RAWRRRRRR" >> dragon.txt

        - name: Test file exits
          run: grep -i "RAWRRRRRR" dragon.txt

        - name: Read file
          run: cat dragon.txt

        - name: checkout Repo files
          run: ls -a